init 2:
# Дополнительные звуки, которые присутствуют в архиве с игрой, но не объявлены в файле ресурсов
    $ sfx_alisa_falls_novoice = "sound/sfx/alisa_falls_novoice.ogg"
    $ sfx_blanket_off = "sound/sfx/blanket_off.ogg"
    $ sfx_catgirl_hiss = "sound/sfx/catgirl_hiss.ogg"
    $ sfx_computer_screen_static = "sound/sfx/computer_screen_static.ogg"
    $ sfx_dinner_jingle_normal = "sound/sfx/dinner_jingle_normal.ogg"
    $ sfx_dinner_jingle_speaker = "sound/sfx/dinner_jingle_speaker.ogg"
    $ sfx_dinner_jingle_speaker_tape = "sound/sfx/dinner_jingle_speaker_tape.ogg"
    $ sfx_hell_crickets_4 = "sound/sfx/hell_crickets_4.ogg"
    $ sfx_jump_into_hole = "sound/sfx/jump_into_hole.ogg"
    $ sfx_jump_into_hole_3 = "sound/sfx/jump_into_hole_3.ogg"
    $ sfx_menu_gate = "sound/sfx/menu_gate.ogg"
    $ sfx_sharkaem_nogami = "art_of_new_life/sound1/sharkaem_nogami.ogg"
    $ Zvonok1 = "art_of_new_life/sound1/Zvonok.ogg"
    $ Perepoloh = "art_of_new_life/sound1/Korobka_padaet.ogg"
    $ miky_svist = "art_of_new_life/sound1/miky_svist.ogg"
    $ Tolchok = "art_of_new_life/sound1/Tolchok.ogg"
    $ kostushki = "art_of_new_life/sound1/kostushki.ogg"